
/*
	AvrLaserVector.h
	This msg file was autogenerated by the Rutgers avr_bridge software.
	*/ 
#ifndef AVRLASERVECTOR_H
#define AVRLASERVECTOR_H
#include "Msg.h"
#include "vector.h"
#include "ros_string.h"


namespace maximus_sensors {
class AvrLaserVector : public Msg{
   public:
	AvrLaserVector();
	AvrLaserVector(uint8_t * data);
	~AvrLaserVector();

	uint16_t bytes();
	uint16_t serialize(uint8_t * out_buffer);
	uint16_t deserialize(uint8_t * data);

	ROS::vector<float> ranges; //fixed at length 18
   private:

}; /***** ending class AvrLaserVector *******/


} /***** ending namespace maximus_sensors *******/

#endif  /****   AVRLASERVECTOR_H    *****/